# Generated by Django 3.0.6 on 2020-07-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.CharField(default='No details provided', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='No number provided', max_length=15),
        ),
    ]
