# Generated by Django 3.0.6 on 2020-07-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0029_auto_20200628_1527'),
        ('shopping_cart', '0003_order_is_helped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theApp.Restaurant'),
        ),
    ]
