# Generated by Django 3.0.6 on 2020-07-20 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_auto_20200720_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 20, 16, 48, 5, 786348)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 20, 16, 48, 5, 786348)),
        ),
    ]
