# Generated by Django 3.0.6 on 2020-07-20 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_auto_20200720_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='timeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
