# Generated by Django 3.0.6 on 2020-05-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_restaurant_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
