# Generated by Django 3.0.4 on 2020-06-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0010_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
