# Generated by Django 3.0.4 on 2020-06-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0011_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
