# Generated by Django 3.0.4 on 2020-06-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0013_auto_20200624_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prices',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='theApp.Price'),
        ),
    ]
