# Generated by Django 3.0.4 on 2020-06-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0014_auto_20200624_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='prices',
        ),
    ]
