# Generated by Django 3.0.4 on 2020-06-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0015_remove_restaurant_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reviews',
        ),
    ]
