# Generated by Django 3.0.4 on 2020-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0016_remove_restaurant_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
