# Generated by Django 3.0.6 on 2020-06-24 08:45

from django.db import migrations, models
import django.db.models.deletion
import theApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0019_auto_20200624_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prices',
            field=models.ForeignKey(default=theApp.models.get_default_price, on_delete=django.db.models.deletion.CASCADE, to='theApp.Price'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reviews',
            field=models.ForeignKey(default=theApp.models.get_default_reviews, on_delete=django.db.models.deletion.CASCADE, to='theApp.Reviews'),
        ),
    ]
