# Generated by Django 3.0.6 on 2020-06-24 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0020_auto_20200624_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theApp.Price'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='reviews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theApp.Reviews'),
        ),
    ]
