# Generated by Django 3.0.6 on 2020-06-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0021_auto_20200624_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prices',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='theApp.Price'),
        ),
    ]
