# Generated by Django 3.0.6 on 2020-06-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0022_auto_20200624_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
