# Generated by Django 3.0.6 on 2020-06-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0023_auto_20200627_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='static/img/blog/main-blog/maxx.jpg', upload_to='static/img/restaurant/'),
        ),
    ]
