# Generated by Django 3.0.6 on 2020-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0025_auto_20200627_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='arise-and-shine.jpg', upload_to='restaurant'),
        ),
    ]
