# Generated by Django 3.0.6 on 2020-06-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0026_auto_20200627_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='This restaurant is nice', max_length=100000),
        ),
    ]
