# Generated by Django 3.0.6 on 2020-06-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0027_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hour',
            field=models.CharField(default='8.00 am to 6.00 pm', max_length=100),
        ),
    ]
