# Generated by Django 3.0.6 on 2020-06-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0028_restaurant_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
